### ISSUE TITLE
Wrap as an npm module

### ISSUE THREAD

**Issue by rtfeldman** [eeue56/elm-static-site#5]
This would be most useful as an npm module instead of as a Python script, which would unlock things like a webpack loader, gulp plugin, etc.

**Comment by Rolograaf** [comment]
Sorry, consider myself still elm-beginner but are interested using elm for personal static website.

Installed Python 3.5.1 for Windows to try elm-static-site out, but get error running `python crawl.py`

```
'.' is not recognized as an internal or external command,
operable program or batch file.
calling examples
```

In windows 10 double clicking the `crawl.py` executes it in a command window, but it is closed so quickly that I cannot read output or error. but I think it is the same as above.

there is a `convert.js` included in `js` folder, does this do the same as the python script?
how can I use it? 
Can we make a npm script like `"build": "node ./js/convert.js"` or something to make that work?

Any possibility getting suggestion of @rtfeldman to be worked out, probably better working cross-platform?

**Comment by eeue56** [comment]
elm-static-html exists instead.

**Comment by Rolograaf** [comment]
https://github.com/eeue56/elm-static-html
