### ISSUE TITLE
Which One Should I Use?

### ISSUE THREAD

**Issue by FaithfulAudio** [eeue56/elm-static-site#8]
Hi, I'd like to use elm to generate static html. On `elm-package install` this threw an error that I have elm 0.18.

I looked at elm-static-html, it seemed to generate a static page, but I'm not sure(after `npm install` and `elm-package install`) I also found elm-static-html-lib. Which one should generate me a static `hello world` page to build from? Thanks for your efforts.

**Comment by eeue56** [comment]
This version is for Elm 0.16 and earlier. You want either: elm-static-html or elm-static-html-lib. I recommend elm-static-html-lib.
